"""Library for managing Architecture Decision Records (ADRs)."""
from __future__ import annotations

import datetime as _dt
import re
from dataclasses import dataclass
from pathlib import Path

import yaml

# Ordered ADR metadata fields mapped to their human-readable table labels.
FIELD_LABELS: dict[str, str] = {
    "id": "ID",
    "name": "Name",
    "description": "Description",
    "status": "Status",
    "date_proposed": "Date proposed",
    "date_accepted": "Date accepted",
    "date_invalidated": "Date invalidated",
    "author": "Author",
    "supersedes": "Supersedes",
    "superseded_by": "Superseded by",
    "tags": "Tags",
}

VALID_STATUSES = {"proposed", "accepted", "superseded", "deprecated", "rejected"}
LIST_FIELDS = {"supersedes", "superseded_by", "tags"}

FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n?(.*)$", re.DOTALL)

ADR_GLOB = "[0-9][0-9][0-9][0-9]-*.md"
ID_PREFIX_RE = re.compile(r"^(\d{4})-.*\.md$")
_TAG_ROW_RE = re.compile(r"^\|\s*(?P<tag>[^|]+?)\s*\|\s*(?P<desc>.*?)\s*\|\s*$")

META_START = "<!-- adr-meta:start -->"
META_END = "<!-- adr-meta:end -->"
EMPTY_DISPLAY = "—"


def slugify(name: str) -> str:
    """Lowercase, hyphenate, strip to a filename-safe slug."""
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


@dataclass
class Adr:
    path: Path
    frontmatter: dict
    body: str


def parse_adr(path) -> Adr:
    text = Path(path).read_text(encoding="utf-8")
    m = FRONTMATTER_RE.match(text)
    if not m:
        raise ValueError(f"{path}: missing or malformed YAML frontmatter")
    fm = yaml.safe_load(m.group(1)) or {}
    return Adr(path=Path(path), frontmatter=fm, body=m.group(2))


def dump_frontmatter(fm: dict) -> str:
    """Serialize frontmatter in canonical field order (only known fields)."""
    ordered = {key: fm.get(key) for key in FIELD_LABELS}
    return yaml.safe_dump(ordered, sort_keys=False, allow_unicode=True).rstrip()


def display_value(field_name: str, value) -> str:
    if value is None or value == "" or value == []:
        return EMPTY_DISPLAY
    if field_name in LIST_FIELDS:
        if isinstance(value, list):
            return ", ".join(str(v) for v in value) if value else EMPTY_DISPLAY
        return str(value)
    return str(value)


def render_meta_table(fm: dict) -> str:
    lines = [META_START, "| Field | Value |", "| --- | --- |"]
    for key, label in FIELD_LABELS.items():
        lines.append(f"| {label} | {display_value(key, fm.get(key))} |")
    lines.append(META_END)
    return "\n".join(lines)


def extract_meta_table(body: str) -> str | None:
    start = body.find(META_START)
    end = body.find(META_END)
    if start == -1 or end == -1 or end < start:
        return None
    return body[start : end + len(META_END)]


def next_id(adr_dir) -> str:
    nums = []
    for p in Path(adr_dir).glob(ADR_GLOB):
        m = ID_PREFIX_RE.match(p.name)
        if m:
            nums.append(int(m.group(1)))
    return f"{(max(nums) + 1) if nums else 1:04d}"


def iter_adrs(adr_dir) -> list[Adr]:
    return [parse_adr(p) for p in sorted(Path(adr_dir).glob(ADR_GLOB))]


def load_tags(tags_path) -> dict[str, str]:
    tags: dict[str, str] = {}
    for line in Path(tags_path).read_text(encoding="utf-8").splitlines():
        m = _TAG_ROW_RE.match(line)
        if not m:
            continue
        tag = m.group("tag").strip()
        desc = m.group("desc").strip()
        if tag.lower() == "tag" or set(tag) <= {"-"}:
            continue  # header / separator rows
        tags[tag] = desc
    return tags


def render_index(adrs: list[Adr]) -> str:
    lines = [
        "# Architecture Decision Records",
        "",
        "Generated by `./scripts/adr index` — do not edit by hand.",
        "",
        "| ID | Name | Status | Tags |",
        "| --- | --- | --- | --- |",
    ]
    for a in adrs:
        fm = a.frontmatter
        link = f"[{fm['id']}]({a.path.name})"
        lines.append(
            f"| {link} | {fm.get('name', '')} | {fm.get('status', '')} "
            f"| {display_value('tags', fm.get('tags'))} |"
        )
    return "\n".join(lines) + "\n"


def validate_adrs(adr_dir) -> list[str]:
    """Return a list of human-readable validation errors (empty == valid)."""
    adr_dir = Path(adr_dir)
    errors: list[str] = []

    tags_path = adr_dir / "_tags.md"
    registry = load_tags(tags_path) if tags_path.exists() else {}
    if not tags_path.exists():
        errors.append("missing tag registry: _tags.md")

    for adr in iter_adrs(adr_dir):
        fm, name = adr.frontmatter, adr.path.name

        for key in FIELD_LABELS:
            if key not in fm:
                errors.append(f"{name}: frontmatter missing field '{key}'")

        status = fm.get("status")
        if status not in VALID_STATUSES:
            errors.append(f"{name}: invalid status '{status}'")

        expected_prefix = f"{fm.get('id')}-"
        if not name.startswith(expected_prefix):
            errors.append(f"{name}: filename does not match id '{fm.get('id')}'")

        table = extract_meta_table(adr.body)
        if table is None:
            errors.append(f"{name}: missing meta table markers")
        elif table != render_meta_table(fm):
            errors.append(f"{name}: meta table drift (table != frontmatter)")

        for tag in fm.get("tags") or []:
            if tag not in registry:
                errors.append(f"{name}: tag '{tag}' not in _tags.md registry")

    index_path = adr_dir / "README.md"
    expected_index = render_index(iter_adrs(adr_dir))
    if not index_path.exists():
        errors.append("missing ADR index: README.md")
    elif index_path.read_text(encoding="utf-8") != expected_index:
        errors.append("ADR index (README.md) is stale — run `./scripts/adr index`")

    return errors


def _today_iso() -> str:
    return _dt.date.today().isoformat()


def compose_adr(fm: dict, body_sections: str) -> str:
    """Build full ADR text: frontmatter + title + meta table + sections."""
    return (
        f"---\n{dump_frontmatter(fm)}\n---\n"
        f"# ADR-{fm['id']}: {fm['name']}\n\n"
        f"{render_meta_table(fm)}\n\n"
        f"{body_sections}"
    )


_DEFAULT_SECTIONS = (
    "## Context and Problem Statement\n\n"
    "_What is the issue we are addressing? One subject only._\n\n"
    "## Decision Drivers\n\n- _driver_\n\n"
    "## Considered Options\n\n- _option_\n\n"
    "## Decision Outcome\n\n"
    "Chosen option: _option_, because _justification_.\n\n"
    "### Consequences\n\n- Good: _benefit_\n- Bad: _cost_\n\n"
    "## Links\n\n- _related ADRs / references_\n"
)


def new_adr(adr_dir, name: str, tags: list[str], author: str,
            today: str | None = None) -> Path:
    adr_dir = Path(adr_dir)
    today = today or _today_iso()
    adr_id = next_id(adr_dir)
    fm = {
        "id": adr_id, "name": name, "description": "", "status": "proposed",
        "date_proposed": today, "date_accepted": None, "date_invalidated": None,
        "author": author, "supersedes": [], "superseded_by": [], "tags": list(tags),
    }
    path = adr_dir / f"{adr_id}-{slugify(name)}.md"
    path.write_text(compose_adr(fm, _DEFAULT_SECTIONS), encoding="utf-8")
    return path


def _rewrite_with_synced_table(adr: Adr) -> None:
    """Persist an ADR re-rendering frontmatter + meta table, preserving sections."""
    table = extract_meta_table(adr.body)
    if table is not None:
        new_body = adr.body.replace(table, render_meta_table(adr.frontmatter), 1)
    else:
        new_body = f"{render_meta_table(adr.frontmatter)}\n\n{adr.body}"
    adr.path.write_text(
        f"---\n{dump_frontmatter(adr.frontmatter)}\n---\n{new_body}", encoding="utf-8"
    )


def accept_adr(path, today: str | None = None) -> None:
    adr = parse_adr(path)
    adr.frontmatter["status"] = "accepted"
    adr.frontmatter["date_accepted"] = today or _today_iso()
    _rewrite_with_synced_table(adr)


def add_tag(tags_path, tag: str, description: str) -> None:
    tags_path = Path(tags_path)
    if tag in load_tags(tags_path):
        return
    text = tags_path.read_text(encoding="utf-8").rstrip("\n")
    tags_path.write_text(f"{text}\n| {tag} | {description} |\n", encoding="utf-8")


def write_index(adr_dir) -> None:
    adr_dir = Path(adr_dir)
    (adr_dir / "README.md").write_text(render_index(iter_adrs(adr_dir)), encoding="utf-8")
